# Generated by Django 6.0.6 on 2026-06-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Pengumuman')),
                ('konten', models.TextField(verbose_name='Isi Pengumuman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif / Tampilkan')),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Daftar Pengumuman',
                'ordering': ['-created_at'],
            },
        ),
    ]
