# Generated by Django 6.0.6 on 2026-06-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0002_pengumuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='aset_id',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Aset ID'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='estimasi_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Estimasi Tanggal Selesai'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='petugas',
            field=models.CharField(blank=True, default='Belum Ditugaskan', max_length=100, null=True, verbose_name='Petugas Lapangan'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='prioritas',
            field=models.CharField(choices=[('Rendah', 'Rendah'), ('Normal', 'Normal'), ('Tinggi', 'Tinggi')], default='Normal', max_length=20, verbose_name='Prioritas Pengerjaan'),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='urgensi',
            field=models.CharField(choices=[('Rendah', 'Rendah'), ('Normal', 'Normal'), ('Tinggi', 'Tinggi'), ('Sangat Tinggi', 'Sangat Tinggi')], default='Normal', max_length=20, verbose_name='Tingkat Urgensi'),
        ),
    ]
