# Generated by Django 6.0.6 on 2026-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0003_pengaduan_aset_id_pengaduan_estimasi_selesai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Diverifikasi', 'Diverifikasi'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20, verbose_name='Status Penanganan'),
        ),
    ]
