# Generated by Django 6.0.6 on 2026-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0004_alter_pengaduan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Profil'),
        ),
    ]
